import type { Vehicle } from "./types";

export const VEHICLES: Vehicle[] = [
  { id: "vw-golf-8-tsi", make: "Volkswagen", model: "Golf 8 1.5 TSI", yearStart: 2020, fuelType: "petrol", consumption: 6.2 },
  { id: "vw-golf-8-tdi", make: "Volkswagen", model: "Golf 8 2.0 TDI", yearStart: 2020, fuelType: "diesel", consumption: 4.5 },
  { id: "vw-passat-tdi", make: "Volkswagen", model: "Passat 2.0 TDI", yearStart: 2014, fuelType: "diesel", consumption: 5.2 },
  { id: "vw-id4", make: "Volkswagen", model: "ID.4", yearStart: 2021, fuelType: "electric", consumption: 17.5 },
  { id: "tesla-m3", make: "Tesla", model: "Model 3 Long Range", yearStart: 2019, fuelType: "electric", consumption: 15.0 },
  { id: "tesla-my", make: "Tesla", model: "Model Y Long Range", yearStart: 2020, fuelType: "electric", consumption: 16.5 },
  { id: "tesla-ms", make: "Tesla", model: "Model S", yearStart: 2017, fuelType: "electric", consumption: 18.5 },
  { id: "tesla-mx", make: "Tesla", model: "Model X", yearStart: 2017, fuelType: "electric", consumption: 21.0 },
  { id: "toyota-rav4-hybrid", make: "Toyota", model: "RAV4 Hybrid", yearStart: 2019, fuelType: "hybrid", consumption: 5.8 },
  { id: "toyota-corolla-hybrid", make: "Toyota", model: "Corolla Hybrid", yearStart: 2019, fuelType: "hybrid", consumption: 4.7 },
  { id: "toyota-yaris", make: "Toyota", model: "Yaris 1.5", yearStart: 2020, fuelType: "petrol", consumption: 5.5 },
  { id: "honda-civic", make: "Honda", model: "Civic 1.5T", yearStart: 2016, fuelType: "petrol", consumption: 6.7 },
  { id: "honda-cr-v-hybrid", make: "Honda", model: "CR-V Hybrid", yearStart: 2019, fuelType: "hybrid", consumption: 6.5 },
  { id: "ford-focus", make: "Ford", model: "Focus 1.0 EcoBoost", yearStart: 2018, fuelType: "petrol", consumption: 6.0 },
  { id: "ford-f150", make: "Ford", model: "F-150 (V6)", yearStart: 2018, fuelType: "petrol", consumption: 12.5 },
  { id: "ford-mach-e", make: "Ford", model: "Mustang Mach-E", yearStart: 2021, fuelType: "electric", consumption: 18.0 },
  { id: "bmw-3", make: "BMW", model: "320i", yearStart: 2019, fuelType: "petrol", consumption: 6.5 },
  { id: "bmw-3d", make: "BMW", model: "320d", yearStart: 2019, fuelType: "diesel", consumption: 4.9 },
  { id: "bmw-i4", make: "BMW", model: "i4 eDrive40", yearStart: 2022, fuelType: "electric", consumption: 17.0 },
  { id: "bmw-ix", make: "BMW", model: "iX xDrive40", yearStart: 2022, fuelType: "electric", consumption: 20.5 },
  { id: "mb-c220d", make: "Mercedes-Benz", model: "C 220 d", yearStart: 2018, fuelType: "diesel", consumption: 5.0 },
  { id: "mb-eqe", make: "Mercedes-Benz", model: "EQE 350", yearStart: 2022, fuelType: "electric", consumption: 18.5 },
  { id: "audi-a4-tdi", make: "Audi", model: "A4 2.0 TDI", yearStart: 2016, fuelType: "diesel", consumption: 5.0 },
  { id: "audi-q4-etron", make: "Audi", model: "Q4 e-tron", yearStart: 2021, fuelType: "electric", consumption: 18.0 },
  { id: "volvo-xc60-d", make: "Volvo", model: "XC60 B4 Diesel", yearStart: 2017, fuelType: "diesel", consumption: 5.7 },
  { id: "volvo-xc40-recharge", make: "Volvo", model: "XC40 Recharge", yearStart: 2020, fuelType: "electric", consumption: 19.5 },
  { id: "polestar-2", make: "Polestar", model: "2 Long Range", yearStart: 2020, fuelType: "electric", consumption: 17.5 },
  { id: "skoda-octavia-tdi", make: "Škoda", model: "Octavia 2.0 TDI", yearStart: 2016, fuelType: "diesel", consumption: 4.7 },
  { id: "skoda-enyaq", make: "Škoda", model: "Enyaq iV 80", yearStart: 2021, fuelType: "electric", consumption: 17.5 },
  { id: "hyundai-ioniq5", make: "Hyundai", model: "Ioniq 5", yearStart: 2021, fuelType: "electric", consumption: 17.5 },
  { id: "kia-ev6", make: "Kia", model: "EV6", yearStart: 2021, fuelType: "electric", consumption: 17.0 },
  { id: "nissan-leaf", make: "Nissan", model: "Leaf 40 kWh", yearStart: 2018, fuelType: "electric", consumption: 17.0 },
  { id: "mazda-cx5", make: "Mazda", model: "CX-5 2.5", yearStart: 2017, fuelType: "petrol", consumption: 7.5 },
  { id: "renault-zoe", make: "Renault", model: "Zoe ZE50", yearStart: 2019, fuelType: "electric", consumption: 16.5 },
  { id: "peugeot-208", make: "Peugeot", model: "208 PureTech", yearStart: 2019, fuelType: "petrol", consumption: 5.4 },
  { id: "porsche-taycan", make: "Porsche", model: "Taycan 4S", yearStart: 2020, fuelType: "electric", consumption: 22.0 },
  { id: "porsche-911", make: "Porsche", model: "911 Carrera", yearStart: 2019, fuelType: "petrol", consumption: 9.8 },
  { id: "toyota-camry", make: "Toyota", model: "Camry 2.5", yearStart: 2018, fuelType: "petrol", consumption: 6.8 },
  { id: "toyota-prius", make: "Toyota", model: "Prius Hybrid", yearStart: 2016, fuelType: "hybrid", consumption: 4.0 },
  { id: "toyota-bz4x", make: "Toyota", model: "bZ4X", yearStart: 2022, fuelType: "electric", consumption: 18.5 },
  { id: "toyota-hilux", make: "Toyota", model: "Hilux 2.4 D-4D", yearStart: 2016, fuelType: "diesel", consumption: 7.2 },
  { id: "toyota-landcruiser", make: "Toyota", model: "Land Cruiser 4.5 D", yearStart: 2016, fuelType: "diesel", consumption: 9.5 },
  { id: "honda-jazz", make: "Honda", model: "Jazz Hybrid", yearStart: 2020, fuelType: "hybrid", consumption: 4.5 },
  { id: "honda-accord", make: "Honda", model: "Accord 1.5T", yearStart: 2018, fuelType: "petrol", consumption: 7.0 },
  { id: "tesla-cybertruck", make: "Tesla", model: "Cybertruck AWD", yearStart: 2024, fuelType: "electric", consumption: 25.0 },
  { id: "vw-id3", make: "Volkswagen", model: "ID.3", yearStart: 2020, fuelType: "electric", consumption: 15.5 },
  { id: "vw-tiguan", make: "Volkswagen", model: "Tiguan 2.0 TDI", yearStart: 2016, fuelType: "diesel", consumption: 5.8 },
  { id: "vw-polo", make: "Volkswagen", model: "Polo 1.0 TSI", yearStart: 2018, fuelType: "petrol", consumption: 5.4 },
  { id: "vw-touran", make: "Volkswagen", model: "Touran 1.5 TSI", yearStart: 2015, fuelType: "petrol", consumption: 6.8 },
  { id: "audi-q5-tdi", make: "Audi", model: "Q5 2.0 TDI", yearStart: 2017, fuelType: "diesel", consumption: 5.9 },
  { id: "audi-etron-gt", make: "Audi", model: "e-tron GT", yearStart: 2021, fuelType: "electric", consumption: 20.5 },
  { id: "audi-a6-tdi", make: "Audi", model: "A6 40 TDI", yearStart: 2018, fuelType: "diesel", consumption: 5.5 },
  { id: "bmw-x3-d", make: "BMW", model: "X3 20d", yearStart: 2018, fuelType: "diesel", consumption: 5.7 },
  { id: "bmw-x5", make: "BMW", model: "X5 xDrive40i", yearStart: 2019, fuelType: "petrol", consumption: 9.2 },
  { id: "mb-glc", make: "Mercedes-Benz", model: "GLC 220 d", yearStart: 2019, fuelType: "diesel", consumption: 6.1 },
  { id: "mb-eqs", make: "Mercedes-Benz", model: "EQS 450+", yearStart: 2021, fuelType: "electric", consumption: 17.5 },
  { id: "volvo-xc90-d", make: "Volvo", model: "XC90 B5 Diesel", yearStart: 2019, fuelType: "diesel", consumption: 6.2 },
  { id: "volvo-ex30", make: "Volvo", model: "EX30 Single Motor", yearStart: 2024, fuelType: "electric", consumption: 16.5 },
  { id: "kia-niro-ev", make: "Kia", model: "Niro EV", yearStart: 2019, fuelType: "electric", consumption: 16.0 },
  { id: "hyundai-tucson-hybrid", make: "Hyundai", model: "Tucson Hybrid", yearStart: 2021, fuelType: "hybrid", consumption: 5.7 },
  { id: "hyundai-kona-ev", make: "Hyundai", model: "Kona Electric", yearStart: 2018, fuelType: "electric", consumption: 14.7 },
  { id: "nissan-qashqai", make: "Nissan", model: "Qashqai 1.3 DIG-T", yearStart: 2019, fuelType: "petrol", consumption: 6.4 },
  { id: "nissan-ariya", make: "Nissan", model: "Ariya 87 kWh", yearStart: 2022, fuelType: "electric", consumption: 18.5 },
  { id: "renault-megane-etech", make: "Renault", model: "Megane E-Tech EV60", yearStart: 2022, fuelType: "electric", consumption: 16.1 },
  { id: "renault-clio", make: "Renault", model: "Clio 1.0 TCe", yearStart: 2019, fuelType: "petrol", consumption: 5.5 },
  { id: "fiat-500e", make: "Fiat", model: "500e", yearStart: 2020, fuelType: "electric", consumption: 14.3 },
  { id: "fiat-panda", make: "Fiat", model: "Panda 1.2", yearStart: 2012, fuelType: "petrol", consumption: 5.7 },
  { id: "mini-cooper-se", make: "MINI", model: "Cooper SE Electric", yearStart: 2020, fuelType: "electric", consumption: 15.2 },
  { id: "subaru-outback", make: "Subaru", model: "Outback 2.5i", yearStart: 2019, fuelType: "petrol", consumption: 8.5 },
  { id: "jeep-wrangler", make: "Jeep", model: "Wrangler 2.0T", yearStart: 2018, fuelType: "petrol", consumption: 11.2 },
  { id: "land-rover-defender", make: "Land Rover", model: "Defender 110 D300", yearStart: 2020, fuelType: "diesel", consumption: 9.2 },
  { id: "rivian-r1t", make: "Rivian", model: "R1T", yearStart: 2022, fuelType: "electric", consumption: 24.5 },
  { id: "lucid-air", make: "Lucid", model: "Air Touring", yearStart: 2022, fuelType: "electric", consumption: 16.5 },

  { id: "kawa-ninja300", make: "Kawasaki", model: "Ninja 300", yearStart: 2013, fuelType: "petrol", consumption: 3.5 },
  { id: "kawa-ninja650", make: "Kawasaki", model: "Ninja 650", yearStart: 2017, fuelType: "petrol", consumption: 4.3 },
  { id: "kawa-z900", make: "Kawasaki", model: "Z900", yearStart: 2017, fuelType: "petrol", consumption: 5.0 },
  { id: "yam-r3", make: "Yamaha", model: "YZF-R3", yearStart: 2015, fuelType: "petrol", consumption: 3.5 },
  { id: "yam-mt07", make: "Yamaha", model: "MT-07", yearStart: 2014, fuelType: "petrol", consumption: 4.0 },
  { id: "yam-mt09", make: "Yamaha", model: "MT-09", yearStart: 2014, fuelType: "petrol", consumption: 5.0 },
  { id: "yam-tenere700", make: "Yamaha", model: "Ténéré 700", yearStart: 2019, fuelType: "petrol", consumption: 4.5 },
  { id: "honda-cbr600", make: "Honda", model: "CBR600RR", yearStart: 2013, fuelType: "petrol", consumption: 5.5 },
  { id: "honda-africa-twin", make: "Honda", model: "Africa Twin 1100", yearStart: 2020, fuelType: "petrol", consumption: 4.8 },
  { id: "honda-grom", make: "Honda", model: "Grom 125", yearStart: 2014, fuelType: "petrol", consumption: 2.2 },
  { id: "ktm-duke390", make: "KTM", model: "390 Duke", yearStart: 2017, fuelType: "petrol", consumption: 3.3 },
  { id: "ktm-1290sd", make: "KTM", model: "1290 Super Duke R", yearStart: 2017, fuelType: "petrol", consumption: 6.0 },
  { id: "bmw-r1250gs", make: "BMW", model: "R 1250 GS", yearStart: 2019, fuelType: "petrol", consumption: 5.2 },
  { id: "bmw-s1000rr", make: "BMW", model: "S 1000 RR", yearStart: 2019, fuelType: "petrol", consumption: 6.5 },
  { id: "ducati-monster", make: "Ducati", model: "Monster 821", yearStart: 2014, fuelType: "petrol", consumption: 5.0 },
  { id: "ducati-panigale", make: "Ducati", model: "Panigale V4", yearStart: 2018, fuelType: "petrol", consumption: 6.8 },
  { id: "triumph-tiger900", make: "Triumph", model: "Tiger 900", yearStart: 2020, fuelType: "petrol", consumption: 5.5 },
  { id: "triumph-street-triple", make: "Triumph", model: "Street Triple 765", yearStart: 2017, fuelType: "petrol", consumption: 4.8 },
  { id: "harley-sportster", make: "Harley-Davidson", model: "Sportster Iron 883", yearStart: 2014, fuelType: "petrol", consumption: 5.0 },
  { id: "harley-fatboy", make: "Harley-Davidson", model: "Fat Boy 114", yearStart: 2018, fuelType: "petrol", consumption: 5.8 },
  { id: "vespa-primavera", make: "Vespa", model: "Primavera 150", yearStart: 2014, fuelType: "petrol", consumption: 2.5 },
  { id: "vespa-gts", make: "Vespa", model: "GTS 300", yearStart: 2014, fuelType: "petrol", consumption: 3.2 },
  { id: "zero-srf", make: "Zero", model: "SR/F (electric bike)", yearStart: 2019, fuelType: "electric", consumption: 9.0 },
  { id: "energica-ego", make: "Energica", model: "Ego (electric bike)", yearStart: 2015, fuelType: "electric", consumption: 11.0 },
];

export function searchVehicles(query: string, limit = 20): Vehicle[] {
  const q = query.trim().toLowerCase();
  if (!q) return VEHICLES.slice(0, limit);
  const tokens = q.split(/\s+/).filter(Boolean);
  return VEHICLES.filter((v) => {
    const hay = `${v.make} ${v.model} ${v.yearStart}`.toLowerCase();
    return tokens.every((t) => hay.includes(t));
  }).slice(0, limit);
}
